httpTimeoutSeconds: 30

models:
  gemini: gemini-2.5-flash
  openai: gpt-5-nano
  ollama: qwen3-coder:latest
  claude: claude-haiku-4-5-20251001

prompts:
  rewrite: |
    You are a professional editor. Improve the following text according to these instructions:

    Objectives:
    1. Correct all spelling and punctuation errors.
    2. Fix all grammatical and syntactical issues.
    3. Keep the meaning and tone as close as possible to the original text.
    
    Style Guidelines
      - Use active voice and clear, simple sentences.
      - Contractions (e.g., “we’re,” “they’re”) are allowed.
      - Maintain a conversational, professional tone suitable for the workplace.
      - Avoid slang, emojis, and overly formal corporate language.
    
    Output Rules
     - Return only the edited text, with no explanations, comments, or formatting other than plain text.
    
    Text to edit:

  translate: "Translate the following text to %s, return only the result: "
  summarize: "Summarize the following text in a clear, concise way: "

baseEndpoint:
  gemini: https://generativelanguage.googleapis.com/v1beta/models/
  ollama: http://localhost:11434/api/generate
  openai: https://api.openai.com/v1/chat/completions
  claude: https://api.anthropic.com/v1/messages

inputFileLimitKB: 128

claude:
  MaxTokens: 1024
  APIVersion: "2023-06-01"

openai:
  Temperature: 1
